# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvrscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvr',
            name='unidade_dvr',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
